services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edutrack
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./analytics:/app/analytics
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=edutrack
      - DB_PORT=5432

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  analytics:
    build: ./analytics
    volumes:
      - ./analytics:/app

volumes:
  postgres_data:
